name:                 HaskellDemo
version:              0.1.0.0
visibility:           public
id:                   HaskellDemo-0.1.0.0-HqGHlKxHXwAKOhxdHpFNcw
key:                  HaskellDemo-0.1.0.0-HqGHlKxHXwAKOhxdHpFNcw
license:              BSD-3-Clause
copyright:            2026
maintainer:           your@email.com
author:               Your Name
homepage:             https://github.com/username/HaskellDemo#readme
description:
    Демонстрационное консольное приложение на Haskell, иллюстрирующее функции, операторы, полиморфизм и классы типов.

abi:                  644bdf6b649a4408db1a937cc6e8878c
exposed:              True
hidden-modules:       Paths_HaskellDemo
import-dirs:
    D:\!!!_RNX_DISK_2027_!!!\YandexDisk\!!!_RNX_REPOS_!!!\HaskellDemo\.stack-work\install\df782e78\lib\x86_64-windows-ghc-9.6.5\HaskellDemo-0.1.0.0-HqGHlKxHXwAKOhxdHpFNcw

library-dirs:
    D:\!!!_RNX_DISK_2027_!!!\YandexDisk\!!!_RNX_REPOS_!!!\HaskellDemo\.stack-work\install\df782e78\lib\x86_64-windows-ghc-9.6.5\HaskellDemo-0.1.0.0-HqGHlKxHXwAKOhxdHpFNcw
    C:\Users\xunir\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\clang64\lib
    C:\Users\xunir\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\clang64\bin

library-dirs-static:
    D:\!!!_RNX_DISK_2027_!!!\YandexDisk\!!!_RNX_REPOS_!!!\HaskellDemo\.stack-work\install\df782e78\lib\x86_64-windows-ghc-9.6.5\HaskellDemo-0.1.0.0-HqGHlKxHXwAKOhxdHpFNcw
    C:\Users\xunir\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\clang64\lib
    C:\Users\xunir\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\clang64\bin

dynamic-library-dirs:
    D:\!!!_RNX_DISK_2027_!!!\YandexDisk\!!!_RNX_REPOS_!!!\HaskellDemo\.stack-work\install\df782e78\lib\x86_64-windows-ghc-9.6.5
    C:\Users\xunir\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\clang64\lib
    C:\Users\xunir\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\clang64\bin

data-dir:
    D:\!!!_RNX_DISK_2027_!!!\YandexDisk\!!!_RNX_REPOS_!!!\HaskellDemo\.stack-work\install\df782e78\share\x86_64-windows-ghc-9.6.5\HaskellDemo-0.1.0.0

hs-libraries:         HSHaskellDemo-0.1.0.0-HqGHlKxHXwAKOhxdHpFNcw
include-dirs:
    C:\Users\xunir\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\clang64\include

depends:              base-4.18.2.1
haddock-interfaces:
    D:\!!!_RNX_DISK_2027_!!!\YandexDisk\!!!_RNX_REPOS_!!!\HaskellDemo\.stack-work\install\df782e78\doc\HaskellDemo-0.1.0.0\HaskellDemo.haddock

haddock-html:
    D:\!!!_RNX_DISK_2027_!!!\YandexDisk\!!!_RNX_REPOS_!!!\HaskellDemo\.stack-work\install\df782e78\doc\HaskellDemo-0.1.0.0
